In [48]:
import sys, os
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [49]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [50]:
net = simpleNet()
print(net.W)

[[ 0.68748308 -0.73245125 -0.53247029]
 [-0.17173943 -1.03034707  0.66357426]]


In [51]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[ 0.25792436 -1.36678311  0.27773466]


In [52]:
np.argmax(p)

np.int64(2)

In [53]:
t = np.array([0, 0, 1])
net.loss(x, t)

np.float64(0.776334086876777)

In [54]:
def f(W):
    return net.loss(x, t)

In [55]:
dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.27063873  0.05330752 -0.32394625]
 [ 0.40595809  0.07996128 -0.48591937]]
