In [35]:
import numpy as np
import matplotlib.pyplot as plt

In [36]:
def function_2(x):
    return x[0]**2 + x[1]**2

In [37]:
def numerical_gradient(f, x):
    h = 1e-4
    grad = np.zeros_like(x)

    for idx in range(x.size):
        tmp_val = x[idx]

        # f(x+h)
        x[idx] = tmp_val + h
        fxh1 = f(x)

        # f(x-h)
        x[idx] = tmp_val - h
        fxh2 = f(x)

        grad[idx] = (fxh1 - fxh2) / (2 * h)
        x[idx] = tmp_val

    return grad

In [38]:
numerical_gradient(function_2, np.array([3.0, 4.0]))

array([6., 8.])

In [39]:
numerical_gradient(function_2, np.array([0.0, 2.0]))

array([0., 4.])

In [40]:

numerical_gradient(function_2, np.array([3.0, 0.0]))

array([6., 0.])